apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: order-invoicer
  name: order-invoicer
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
      labels:
        app: order-invoicer
    spec:
      containerConcurrency: 0
      containers:
      - image: quay.io/redhattraining/order-invoicer:1.0
        ports:
        - containerPort: 5000
          protocol: TCP
