apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: orders-to-invoice-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: orders-to-invoice
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: order-invoicer
