apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: order-processor
  name: order-processor
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
      labels:
        app: order-processor
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: INVOICING_SINK
          value: http://orders-to-invoice-kn-channel.developer-eventing-filter.svc.cluster.local
        - name: FRAUD_SINK
          value: http://orders-to-investigate-kn-channel.developer-eventing-filter.svc.cluster.local
        image: quay.io/redhattraining/order-processor:1.0
        ports:
        - containerPort: 5000
          protocol: TCP
