---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "<<unknown>>"
    app.quarkus.io/build-timestamp: "2023-11-07 - 11:25:33 +0000"
    app.quarkus.io/commit-id: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  name: "quarkers-mining-service"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "<<unknown>>"
    app.quarkus.io/build-timestamp: "2023-11-07 - 11:25:33 +0000"
    app.quarkus.io/commit-id: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  name: "quarkers-mining-service"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "<<unknown>>"
    app.quarkus.io/build-timestamp: "2023-11-07 - 11:25:33 +0000"
    app.quarkus.io/commit-id: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  name: "quarkers-mining-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "quarkers-mining-service"
      app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: "<<unknown>>"
        app.quarkus.io/build-timestamp: "2023-11-07 - 11:25:33 +0000"
        app.quarkus.io/commit-id: "<<unknown>>"
      labels:
        app.kubernetes.io/name: "quarkers-mining-service"
        app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "student/quarkers-mining-service:1.0.0-SNAPSHOT"
        imagePullPolicy: "Always"
        name: "quarkers-mining-service"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "quarkers-mining-service"
