---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2023-11-07 - 11:25:33 +0000"
    app.openshift.io/vcs-url: "<<unknown>>"
    app.quarkus.io/commit-id: "<<unknown>>"
    app.quarkus.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "quarkers-mining-service"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2023-11-07 - 11:25:33 +0000"
    app.openshift.io/vcs-url: "<<unknown>>"
    app.quarkus.io/commit-id: "<<unknown>>"
    app.quarkus.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "quarkers-mining-service"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  type: "ClusterIP"
---
apiVersion: "image.openshift.io/v1"
kind: "ImageStream"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2023-11-07 - 11:25:33 +0000"
    app.openshift.io/vcs-url: "<<unknown>>"
    app.quarkus.io/commit-id: "<<unknown>>"
    app.quarkus.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "openjdk-11-rhel7"
spec:
  dockerImageRepository: "registry.access.redhat.com/openjdk/openjdk-11-rhel7"
---
apiVersion: "image.openshift.io/v1"
kind: "ImageStream"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2023-11-07 - 11:25:33 +0000"
    app.openshift.io/vcs-url: "<<unknown>>"
    app.quarkus.io/commit-id: "<<unknown>>"
    app.quarkus.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "quarkers-mining-service"
spec: {}
---
apiVersion: "build.openshift.io/v1"
kind: "BuildConfig"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2023-11-07 - 11:25:33 +0000"
    app.openshift.io/vcs-url: "<<unknown>>"
    app.quarkus.io/commit-id: "<<unknown>>"
    app.quarkus.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "quarkers-mining-service"
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "quarkers-mining-service:1.0.0-SNAPSHOT"
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "openjdk-11-rhel7:latest"
---
apiVersion: "apps.openshift.io/v1"
kind: "DeploymentConfig"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2023-11-07 - 11:25:33 +0000"
    app.openshift.io/vcs-url: "<<unknown>>"
    app.quarkus.io/commit-id: "<<unknown>>"
    app.quarkus.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "quarkers-mining-service"
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: "quarkers-mining-service"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: "2023-11-07 - 11:25:33 +0000"
        app.openshift.io/vcs-url: "<<unknown>>"
        app.quarkus.io/commit-id: "<<unknown>>"
        app.quarkus.io/vcs-url: "<<unknown>>"
      labels:
        app.kubernetes.io/name: "quarkers-mining-service"
        app.kubernetes.io/version: "1.0.0-SNAPSHOT"
        app.openshift.io/runtime: "quarkus"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "JAVA_APP_JAR"
          value: "/deployments/quarkers-mining-service-1.0.0-SNAPSHOT-runner.jar"
        - name: "JAVA_LIB_DIR"
          value: "/deployments/lib"
        - name: "JAVA_CLASSPATH"
          value: "/deployments/lib/io.quarkus.quarkus-development-mode-spi-1.4.2.Final.jar:/deployments/lib/org.reactivestreams.reactive-streams-1.0.3.jar:/deployments/lib/io.smallrye.reactive.mutiny-0.4.4.jar:/deployments/lib/io.quarkus.security.quarkus-security-1.1.0.Final.jar:/deployments/lib/jakarta.el.jakarta.el-api-3.0.3.jar:/deployments/lib/jakarta.interceptor.jakarta.interceptor-api-1.2.5.jar:/deployments/lib/jakarta.enterprise.jakarta.enterprise.cdi-api-2.0.2.jar:/deployments/lib/io.netty.netty-codec-4.1.45.Final.jar:/deployments/lib/io.netty.netty-handler-4.1.45.Final.jar:/deployments/lib/io.quarkus.quarkus-netty-1.4.2.Final.jar:/deployments/lib/io.netty.netty-common-4.1.45.Final.jar:/deployments/lib/io.netty.netty-buffer-4.1.45.Final.jar:/deployments/lib/io.netty.netty-transport-4.1.45.Final.jar:/deployments/lib/io.netty.netty-codec-socks-4.1.45.Final.jar:/deployments/lib/io.netty.netty-handler-proxy-4.1.45.Final.jar:/deployments/lib/io.netty.netty-codec-http-4.1.45.Final.jar:/deployments/lib/io.netty.netty-codec-http2-4.1.45.Final.jar:/deployments/lib/io.netty.netty-resolver-4.1.45.Final.jar:/deployments/lib/io.netty.netty-codec-dns-4.1.45.Final.jar:/deployments/lib/io.netty.netty-resolver-dns-4.1.45.Final.jar:/deployments/lib/io.vertx.vertx-core-3.8.5.jar:/deployments/lib/io.quarkus.quarkus-vertx-core-1.4.2.Final.jar:/deployments/lib/io.vertx.vertx-web-common-3.8.5.jar:/deployments/lib/io.vertx.vertx-auth-common-3.8.5.jar:/deployments/lib/io.vertx.vertx-bridge-common-3.8.5.jar:/deployments/lib/io.vertx.vertx-web-3.8.5.jar:/deployments/lib/io.quarkus.quarkus-vertx-http-1.4.2.Final.jar:/deployments/lib/org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-core-spi-4.5.3.Final.jar:/deployments/lib/org.eclipse.microprofile.config.microprofile-config-api-1.4.jar:/deployments/lib/org.jboss.resteasy.resteasy-core-4.5.3.Final.jar:/deployments/lib/com.sun.activation.jakarta.activation-1.2.1.jar:/deployments/lib/io.quarkus.quarkus-resteasy-common-1.4.2.Final.jar:/deployments/lib/jakarta.validation.jakarta.validation-api-2.0.2.jar:/deployments/lib/io.quarkus.quarkus-resteasy-server-common-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-resteasy-1.4.2.Final.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-databind-2.10.3.jar:/deployments/lib/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.10.3.jar:/deployments/lib/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.10.3.jar:/deployments/lib/com.fasterxml.jackson.module.jackson-module-parameter-names-2.10.3.jar:/deployments/lib/io.quarkus.quarkus-jackson-1.4.2.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-jaxb-provider-4.5.3.Final.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-core-2.10.3.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-annotations-2.10.3.jar:/deployments/lib/com.fasterxml.jackson.jaxrs.jackson-jaxrs-base-2.10.3.jar:/deployments/lib/jakarta.activation.jakarta.activation-api-1.2.1.jar:/deployments/lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.10.3.jar:/deployments/lib/com.fasterxml.jackson.jaxrs.jackson-jaxrs-json-provider-2.10.3.jar:/deployments/lib/com.github.fge.btf-1.2.jar:/deployments/lib/com.github.fge.msg-simple-1.1.jar:/deployments/lib/com.github.fge.jackson-coreutils-1.6.jar:/deployments/lib/com.github.fge.json-patch-1.9.jar:/deployments/lib/com.google.guava.failureaccess-1.0.1.jar:/deployments/lib/com.google.guava.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/deployments/lib/com.google.guava.guava-27.0.1-jre.jar:/deployments/lib/org.jboss.logging.jboss-logging-3.3.2.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-jackson2-provider-4.5.3.Final.jar:/deployments/lib/org.jboss.spec.javax.xml.bind.jboss-jaxb-api_2.3_spec-2.0.0.Final.jar:/deployments/lib/io.quarkus.quarkus-resteasy-jackson-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-kubernetes-client-internal-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-openshift-1.4.2.Final.jar:/deployments/lib/jakarta.annotation.jakarta.annotation-api-1.3.5.jar:/deployments/lib/jakarta.inject.jakarta.inject-api-1.0.jar:/deployments/lib/io.smallrye.config.smallrye-config-common-1.7.0.jar:/deployments/lib/io.smallrye.config.smallrye-config-1.7.0.jar:/deployments/lib/org.jboss.logmanager.jboss-logmanager-embedded-1.0.4.jar:/deployments/lib/org.jboss.logging.jboss-logging-annotations-2.1.0.Final.jar:/deployments/lib/org.jboss.threads.jboss-threads-3.1.1.Final.jar:/deployments/lib/org.slf4j.slf4j-api-1.7.30.jar:/deployments/lib/org.jboss.slf4j.slf4j-jboss-logging-1.2.0.Final.jar:/deployments/lib/org.graalvm.sdk.graal-sdk-19.3.1.jar:/deployments/lib/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar:/deployments/lib/io.quarkus.quarkus-core-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-datasource-common-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-datasource-1.4.2.Final.jar:/deployments/lib/org.jboss.jboss-transaction-spi-7.6.0.Final.jar:/deployments/lib/org.jboss.spec.javax.resource.jboss-connector-api_1.7_spec-1.0.0.Final.jar:/deployments/lib/org.jboss.narayana.jta.narayana-jta-5.10.4.Final.jar:/deployments/lib/org.jboss.narayana.jts.narayana-jts-integration-5.10.4.Final.jar:/deployments/lib/io.agroal.agroal-api-1.7.jar:/deployments/lib/io.agroal.agroal-narayana-1.7.jar:/deployments/lib/io.agroal.agroal-pool-1.7.jar:/deployments/lib/io.quarkus.quarkus-vault-spi-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-agroal-1.4.2.Final.jar:/deployments/lib/org.eclipse.microprofile.reactive-streams-operators.microprofile-reactive-streams-operators-api-1.0.1.jar:/deployments/lib/org.eclipse.microprofile.reactive-streams-operators.microprofile-reactive-streams-operators-core-1.0.1.jar:/deployments/lib/io.reactivex.rxjava2.rxjava-2.2.19.jar:/deployments/lib/io.smallrye.reactive.smallrye-reactive-streams-operators-1.0.10.jar:/deployments/lib/io.smallrye.smallrye-context-propagation-jta-1.0.11.jar:/deployments/lib/io.smallrye.reactive.smallrye-reactive-converter-api-1.0.10.jar:/deployments/lib/io.quarkus.quarkus-narayana-jta-1.4.2.Final.jar:/deployments/lib/net.bytebuddy.byte-buddy-1.10.7.jar:/deployments/lib/antlr.antlr-2.7.7.jar:/deployments/lib/org.jboss.jandex-2.1.3.Final.jar:/deployments/lib/com.fasterxml.classmate-1.3.4.jar:/deployments/lib/org.dom4j.dom4j-2.1.1.jar:/deployments/lib/org.hibernate.common.hibernate-commons-annotations-5.1.0.Final.jar:/deployments/lib/org.hibernate.hibernate-core-5.4.14.Final.jar:/deployments/lib/org.hibernate.hibernate-graalvm-5.4.14.Final.jar:/deployments/lib/org.glassfish.jaxb.txw2-2.3.3-b02.jar:/deployments/lib/com.sun.istack.istack-commons-runtime-3.0.10.jar:/deployments/lib/org.glassfish.jaxb.jaxb-runtime-2.3.3-b02.jar:/deployments/lib/jakarta.persistence.jakarta.persistence-api-2.2.3.jar:/deployments/lib/jakarta.transaction.jakarta.transaction-api-1.3.3.jar:/deployments/lib/com.google.errorprone.error_prone_annotations-2.2.0.jar:/deployments/lib/com.github.ben-manes.caffeine.caffeine-2.8.0.jar:/deployments/lib/org.hibernate.quarkus-local-cache-0.1.0.jar:/deployments/lib/io.quarkus.quarkus-caffeine-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-hibernate-orm-1.4.2.Final.jar:/deployments/lib/io.quarkus.arc.arc-1.4.2.Final.jar:/deployments/lib/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.0.1.jar:/deployments/lib/io.quarkus.quarkus-arc-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-panache-common-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-hibernate-orm-panache-1.4.2.Final.jar:/deployments/lib/org.postgresql.postgresql-42.2.12.jar:/deployments/lib/io.quarkus.quarkus-jdbc-postgresql-1.4.2.Final.jar"
        - name: "JAVA_OPTIONS"
          value: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
        image: "student/quarkers-mining-service:1.0.0-SNAPSHOT"
        imagePullPolicy: "Always"
        name: "quarkers-mining-service"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "quarkers-mining-service"
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - "quarkers-mining-service"
      from:
        kind: "ImageStreamTag"
        name: "quarkers-mining-service:1.0.0-SNAPSHOT"
    type: "ImageChange"
