apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
  name: orders-dispatcher
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-channel
    namespace: developer-eventing-filter
